[package]
name = "aidos-rs"
version = "0.1.0"
authors = ["nokaa <nokaa@cock.li>"]

[dependencies]
env_logger = "0.3.5"
log = "0.3.6"
hayaku = { git = "https://github.com/nokaa/hayaku" }

[dependencies.toml]
version = "0.2.1"
default-features = false
features = ["serde"]
